### ISSUE TITLE
[Backend] - CRUD

### ISSUE THREAD

**Issue by Zharlock** [Zharlock/K-D#1]

**Comment by tralki** [comment]
# Implementar #
Costumer - CRUD 
Pet - CRUD
Oferta - CRUD
Agendamento - CRUD
Costumer type - CRUD
Metudo de pagamento - CRUD
Funcionario - CRUD
Encloger - CRUD
Checkin - CRUD
Checkout - CRUD
Logs - CRUD

**Comment by Zharlock** [comment]
This Issue is pending of #4

**Comment by tralki** [comment]
CRUD for Customer done

**Comment by Zharlock** [comment]
CRUD for each table implemented

**Comment by tralki** [comment]
# in need
New table images was added and the CRUD for it still needs do be done
