### ISSUE TITLE
[Frontend] - Login/Register page

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#17]
The Login/Register page is going to include:

- Form to Login (username or email/password).
- Form to Register (email/name/password/age/pet_owner/type of customer).

**Comment by Cuerry** [comment]
# Login/Register page Design #
This is how the login page looks like.
![image](https://github.com/Zharlock/K-D/assets/117875054/0ea58b31-f0ec-4add-8e39-e28b694c9bc5)

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/b62b92a5-6331-4544-84cb-6293d474da93)
![image](https://github.com/Zharlock/K-D/assets/117875054/ba43c9e6-b6ba-4acd-b7db-d82abfaa911a)
