### ISSUE TITLE
[Frontend] - Home Page/News/Dogs for Adoption 

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#18]
The Home page is going to include:

- Carousel Image (News).
- Random List of Dog/Cat (Name/Animal/Race/Age/~~Porte(Dogs)~~/Gender).

**Comment by Cuerry** [comment]
# Home Page Design #
The look of Home page right now:
![image](https://github.com/Zharlock/K-D/assets/117875054/618d5b45-e2fb-411f-aa74-38917aecd426)

> Home page design can change

**Comment by Cuerry** [comment]
# Adoption Pet List error #
In adoption page the list of each type of pet is not showing any image.

![image](https://github.com/Zharlock/K-D/assets/117875054/0342552c-b660-46a0-ae53-d51a0ccbc611)

**Comment by Cuerry** [comment]
# Adoption Pet List error (solved) #
The filters were wrong on each pet list.
![image](https://github.com/Zharlock/K-D/assets/117875054/1b7da431-ddb2-457e-91e4-c96ac85a9858)

**Comment by Cuerry** [comment]
# Home Page Design #
The look of Home page right now:
![image](https://github.com/Zharlock/K-D/assets/117875054/80ad2709-addb-43b5-b54c-edfdff6ec46c)

> Home page design can change

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/6f688e77-b582-4f5a-b0b1-c1ca504a38a6)
![image](https://github.com/Zharlock/K-D/assets/117875054/9106adaf-302f-476e-9821-fa3c204163dc)
