### ISSUE TITLE
[Frontend] - Dog/Cat List for Adoption page

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#19]
The Dog/Cat list for adoption is going to include:

- List of all Dogs/Cats (Name/Animal/Race/Age/~~Porte(Dogs)~~).
- Adoption Selection (Customer can choose).

**Comment by Cuerry** [comment]
# Adoption Pet List error #
In adoption page the list of each type of pet is not showing any image.

![image](https://github.com/Zharlock/K-D/assets/117875054/0342552c-b660-46a0-ae53-d51a0ccbc611)

**Comment by Cuerry** [comment]
# Adoption Pet List error (solved) #
The filters were wrong on each pet list.
![image](https://github.com/Zharlock/K-D/assets/117875054/1b7da431-ddb2-457e-91e4-c96ac85a9858)

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/67a07965-c863-453c-b74e-d5cf5e3529d6)
![image](https://github.com/Zharlock/K-D/assets/117875054/6761f2b2-06bc-4972-a002-a44029bdd28d)
![image](https://github.com/Zharlock/K-D/assets/117875054/8c659c16-6d40-4dc0-8e18-078d2afa4612)
![image](https://github.com/Zharlock/K-D/assets/117875054/23432d89-2480-474b-afb5-0dee5d20c28e)
