### ISSUE TITLE
[Backend] - Choose programming language and framework

### ISSUE THREAD

**Issue by Zharlock** [Zharlock/K-D#2]
To code the Backend we need to define what programming language and what framework to use.
The Options for the languages are the following:

1. Javascript
2. Python ****
3. JAVA
4. C#
5. PHP

**Comment by Zharlock** [comment]
The Options for the frameworks are the following:

1. Django (Python)
2. FastAPI (Python) *****
3. Swagger + Express (JavaScript)
4. NET Framework

**Comment by Zharlock** [comment]
@tralki @Cuerry @MrRodrigo20 @Brunor118 @Bagulho358
Please give your feedback.

**Comment by tralki** [comment]
> @tralki @Cuerry @MrRodrigo20 @Brunor118 @Bagulho358 Please give your feedback.

Python & FastAPI

**Comment by MrRodrigo20** [comment]
Python & FastAPI

**Comment by Brunor118** [comment]
Python e FastAPI

**Comment by Cuerry** [comment]
> @tralki @Cuerry @MrRodrigo20 @Brunor118 @Bagulho358
> Please give your feedback.

I recommend Python and FastAPI

**Comment by Bagulho358** [comment]
Python and FastAPI

**Comment by Agostinho93** [comment]
Python & FastAPI

**Comment by Zharlock** [comment]
After discussing the different options we opt for Python and FastAPI because:

1. Python is easier to use and more flexible.
2. FastAPI auto generates documentation (Swagger doc).
3. Easy to search for FastAPI examples.
