### ISSUE TITLE
[Frontend] - Plan's page

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#21]
Service Options:
 - button schedule
 - button to adopt a pet
 - plan for the customer pet

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/69871fa3-ec7f-4a5d-8bdb-826e325fa3e9)
![image](https://github.com/Zharlock/K-D/assets/117875054/955c4ed9-949d-4e4d-bd76-9f85fc3525a5)
![image](https://github.com/Zharlock/K-D/assets/117875054/c8a9cca5-54bd-4f27-8e2e-fb991505e85f)
![image](https://github.com/Zharlock/K-D/assets/117875054/065ea9a7-bf13-49e8-a6a5-7c16998af0a4)

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/fab89cfd-237d-49d1-b8cc-775970fcaa41)

![image](https://github.com/Zharlock/K-D/assets/117875054/68ac91e7-0e2b-4232-a33f-ff1a5b87113d)

![image](https://github.com/Zharlock/K-D/assets/117875054/1641dd58-2e5f-4ef5-b55c-bf9299828e3d)

![image](https://github.com/Zharlock/K-D/assets/117875054/f6b8e6f7-f6cb-41e4-8d70-9340d2ac3b89)

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/5f3b6226-1fd4-41af-97da-47cedeefd8c3)
![image](https://github.com/Zharlock/K-D/assets/117875054/ed84d210-2ac0-4ced-bf95-235a58013a73)
![image](https://github.com/Zharlock/K-D/assets/117875054/5e203a1e-cd3e-4f00-9316-aaf5212c8052)
