### ISSUE TITLE
[Frontend] - Pay method page

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#23]
The pay method is going to include:

- Customer can choose the method of payment.
- Fields to introduce the credit card info and leave a donation with the amount(€).

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/87bb9195-4bb8-4acf-962d-e89b44ed8c9c)
![image](https://github.com/Zharlock/K-D/assets/117875054/e4eed9d4-853b-42af-a734-2a8b14b30061)
