### ISSUE TITLE
[Frontend] - Donations page

### ISSUE THREAD

**Issue by Brunor118** [Zharlock/K-D#24]
In the donations page the customer will have different options with Default amount options and a custom option.

**Comment by Lucas2665** [comment]
![Image](https://github.com/Zharlock/K-D/assets/72558588/76f1d13e-5d21-4949-8ae7-b671fc10c5c6)

**Comment by Cuerry** [comment]
# Donations Page #
The look of the donation page right now.
![image](https://github.com/Zharlock/K-D/assets/117875054/01abc804-0671-405b-bc60-2f9c1a3f48da)

**Comment by Cuerry** [comment]
The look of the donation page right now.
![image](https://github.com/Zharlock/K-D/assets/117875054/7ef76918-24c1-4c65-a794-d78b93ad50a9)
![image](https://github.com/Zharlock/K-D/assets/117875054/60df469f-d0cf-448f-a064-148e82d1b526)

**Comment by Cuerry** [comment]
![image](https://github.com/Zharlock/K-D/assets/117875054/b87239f9-a5ce-4b90-a9d9-c15b279e4cd4)
![image](https://github.com/Zharlock/K-D/assets/117875054/c159b805-4358-4a3d-86fb-20fdcc3f1564)
