### ISSUE TITLE
[DB] - Implementation of a Picture Table

### ISSUE THREAD

**Issue by Zharlock** [Zharlock/K-D#28]
For the implementation of pictures in the Frontend, the backend team had to add a table for the pictures to be stored

**Comment by Zharlock** [comment]
We need to run the new SQL Code.
And add to the CRUD #1

**Comment by tralki** [comment]
### Table implemented
![image](https://github.com/Zharlock/K-D/assets/67386789/70b196c7-e47a-4547-95cd-2b39577f4cb8)
