### ISSUE TITLE
[Backend] - Integration of APIs into Google Cloud

### ISSUE THREAD

**Issue by Bagulho358** [Zharlock/K-D#30]
To solve the communication problem between the backend and the frontend, we need to install and configure the backend in the cloud.
We chose the Google Cloud platform.

**Comment by tralki** [comment]
### Update
VM is already created , it has a static api , and python3.11 is already installed

**Comment by Bagulho358** [comment]
Installed and configured the API on Google Cloud. tested and working in outsystems integration.
