### ISSUE TITLE
[Planning] - Divide Teams

### ISSUE THREAD

**Issue by Zharlock** [Zharlock/K-D#4]
Make teams for:

1. Backend
2. Frontend

**Comment by Cuerry** [comment]
I can handle the Frontend. @Zharlock give me Frontend Label, pls.

**Comment by tralki** [comment]
I would like to work no back end

**Comment by tralki** [comment]
> I would like to work on back end

**Comment by Zharlock** [comment]
The teams will be the following:

# Backend/DB #

@tralki 
@Zharlock 
@Bagulho358 
@MrRodrigo20 

# Frontend #

@Cuerry 
@Brunor118 
@Agostinho93 
Lucas
