### ISSUE TITLE
[Planning] - Weekly Status

### ISSUE THREAD

**Issue by Zharlock** [Zharlock/K-D#5]
This issue will be use to document who is going to give the status every week.

In the first week (22/11) it will be:
**@tralki**

[Apresentação_22_11.pptx](https://github.com/Zharlock/K-D/files/13452993/Apresentacao_22_11.pptx)

**Comment by tralki** [comment]
[Apresentação_22_11.pptx](https://github.com/Zharlock/K-D/files/13452993/Apresentacao_22_11.pptx)

**Comment by Cuerry** [comment]
In the first week (23/11) it will be:
**@Brunor118**

[Apresentação_23_11_Gestor2.pptx](https://github.com/Zharlock/K-D/files/13452998/Apresentacao_23_11_Gestor2.pptx)

**Comment by Brunor118** [comment]
[Apresentação_23_11_Gestor2.pptx](https://github.com/Zharlock/K-D/files/13452998/Apresentacao_23_11_Gestor2.pptx)

**Comment by tralki** [comment]
In second week (29/11) it will be:
**@MrRodrigo20**

**Comment by Zharlock** [comment]
In second week (30/11) it will be:
**@Lucas2665**

**Comment by Zharlock** [comment]
In the third week (6/12) it will be:
**@Agostinho93**

**Comment by Cuerry** [comment]
In the fourth week (14/12) it will be:
**@Zharlock**
**@Cuerry**
**@Bagulho358** 

[K&D Application Development.pptx](https://github.com/Zharlock/K-D/files/13678011/K.D.Application.Development.pptx)

**Comment by Cuerry** [comment]
in the fourth week (14/12) it will be;
@Bagulho358

**Comment by Cuerry** [comment]
In the fifth week (22/12) it will be:
**@tralki**
