### ISSUE TITLE
[Planning] - Work Breakdown Structure

### ISSUE THREAD

**Issue by tralki** [Zharlock/K-D#8]
# Warning #
Work Breakdown Structure needs to be done until next wednesday

**Comment by AlexDias95** [comment]
@tralki @Zharlock @Cuerry @MrRodrigo20 @Brunor118 @Agostinho93 @Bagulho358 

Some notes about this topic:

- **[Backend] - Installation of requirements** - Should be divided into multiple issues (10 issues minimum)
The issue appears as closed, did you have already developed all the code? Every time you close an issue, please provide evidences like some pieces of code or images

- **[Frontend] - Webpage's features and options** - Should be divided into multiple issues (9 issues minimum)

**Comment by AlexDias95** [comment]
Example of issues created in another project:

<img width="630" alt="Captura de ecrã 2023-11-18, às 10 29 44" src="https://github.com/Zharlock/K-D/assets/47275399/8f1f77d3-a1f5-42e8-ba36-c585fa17df81">

**Comment by AlexDias95** [comment]
Create more **"micro tasks"**

**Comment by Cuerry** [comment]
Ok @AlexDias95, thank you.
